[package]
name = "z80"
version = "0.1.0"
edition = "2021"

[dependencies]
parser-macros = { path = "../../parser-macros" }
utils = { path = "../../utils" }
nom = "8.0.0"

[lib]
name = "z80"
path = "src/lib.rs"

[[bin]]
name = "z80"
path = "src/main.rs"
