[workspace]
members = [
    "backend",
    "backend/z80"
, "utils"]

[package]
name = "plm"
version = "0.1.0"
edition = "2021"

[dependencies]
backend = { path = "backend" }
utils = { path = "utils" }
parser-macros = { path = "parser-macros" }
