name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Frontend test
      run: cargo test --verbose --package plm
    - name: Backend test
      run: cargo test --verbose --package backend
    - name: Z80 test
      run: cargo test --verbose --package z80
